version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: org.apache.tomcat:tomcat-catalina
      - dependency-name: jakarta.annotation:jakarta.annotation-api
        versions:
          - ">= 2"
  - package-ecosystem: "maven"
    directory: "/8.5"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: org.apache.tomcat:tomcat-catalina
        versions:
          - ">= 9.0"
  - package-ecosystem: "maven"
    directory: "/9.0"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: org.apache.tomcat:tomcat-catalina
        versions:
          - ">= 10.0"
  - package-ecosystem: "maven"
    directory: "/10.1"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: org.apache.tomcat:tomcat-catalina
        versions:
          - ">= 10.2"
