version: 2
updates:
  - package-ecosystem: github-actions
    directory: '/'
    schedule:
      interval: daily
  - package-ecosystem: maven
    directory: '/'
    labels:
      - dependencies
    schedule:
      interval: daily
    ignore:
      - dependency-name: jakarta.annotation:jakarta.annotation-api
        update-types:
          - version-update:semver-major
          - version-update:semver-minor
      - dependency-name: org.apache.tomcat:tomcat-catalina
      - dependency-name: org.infinispan:infinispan-bom
        update-types:
          - version-update:semver-major
          - version-update:semver-minor
      - dependency-name: org.wildfly.clustering:wildfly-clustering-bom
        update-types:
          - version-update:semver-major
          - version-update:semver-minor
  - package-ecosystem: maven
    directory: '/11.0'
    labels:
      - dependencies
    schedule:
      interval: daily
    ignore:
      - dependency-name: org.apache.tomcat:tomcat-catalina
        versions:
          - "[12,)"
  - package-ecosystem: maven
    directory: '/10.1'
    labels:
      - dependencies
    schedule:
      interval: daily
    ignore:
      - dependency-name: org.apache.tomcat:tomcat-catalina
        versions:
          - "[11,)"
  - package-ecosystem: maven
    directory: '/9.0'
    labels:
      - dependencies
    schedule:
      interval: daily
    ignore:
      - dependency-name: org.apache.tomcat:tomcat-catalina
        versions:
          - "[10,)"
